import { FaPlus } from "react-icons/fa";

export function getAlunos() {
    return [
        {
            id: 1,
            nome: "Maria das Rosas Flores",
            email: "maria@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 5,
            nPostsForunsAv: 5,
            quizzesRealiz: "100%",
            tarefasEnv: "100%",
            tempoMedio: 120,
            // desempenho
            flagDesempenho: 5,
            mediaNotas: "9.2",
            compMedia: 120,
            ativAbaixoMedia: 0,
            // motivacao
            flagMotivacao: 5,
            partForunsNaoObrig: "95%",
            nVisuCompl: 42,
            nInter: 28,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 5,
            nMsgsAlunoProf: 8,
            nMsgsPriv: 3,
            partForunsDocente: "100%",
            sentMsgsPriv: "Positivo",
            freqContAlunoProf: "Alta",
            // desistencia
            flagDesistencia: false,
            nNotasAbaixoMedia: 0,
            // reutilizaveis
            sentMsgs: "Positivo",
            nAcessos: 6,
            frequenciaLogin: "0,86",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 100,
        },
        {
            id: 2,
            nome: "José Pedro Ribeiro",
            email: "jose@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 4,
            nPostsForunsAv: 2,
            quizzesRealiz: "80%",
            tarefasEnv: "100%",
            tempoMedio: 110,
            // desempenho
            flagDesempenho: 4,
            mediaNotas: "8.1",
            compMedia: 105,
            ativAbaixoMedia: 1,
            // motivacao
            flagMotivacao: 4,
            partForunsNaoObrig: "85%",
            nVisuCompl: 35,
            nInter: 20,
            // profundidade cognitiva
            flagProfCog: 2,
            profCogForuns: 3,
            profCogQuizzes: 2,
            profCogTarefas: 1,
            // relacao aluno-professor
            flagRelAlunoProf: 4,
            nMsgsAlunoProf: 5,
            nMsgsPriv: 2,
            partForunsDocente: "90%",
            sentMsgsPriv: "Positivo",
            freqContAlunoProf: "Média",
            // desistencia
            flagDesistencia: false,
            nNotasAbaixoMedia: 1,
            // reutilizaveis
            sentMsgs: "Neutro",
            nAcessos: 10,
            frequenciaLogin: "1,42",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 95,
        },
        {
            id: 3,
            nome: "Márcio Dantas",
            email: "marcio@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 3,
            nPostsForunsAv: 4,
            quizzesRealiz: "100%",
            tarefasEnv: "0%",
            tempoMedio: 60,
            // desempenho
            flagDesempenho: 3,
            mediaNotas: "6.8",
            compMedia: 92,
            ativAbaixoMedia: 3,
            // motivacao
            flagMotivacao: 3,
            partForunsNaoObrig: "60%",
            nVisuCompl: 28,
            nInter: 15,
            // profundidade cognitiva
            flagProfCog: 0,
            profCogForuns: 0,
            profCogQuizzes: 0,
            profCogTarefas: 0,
            // relacao aluno-professor
            flagRelAlunoProf: 3,
            nMsgsAlunoProf: 2,
            nMsgsPriv: 1,
            partForunsDocente: "75%",
            sentMsgsPriv: "Neutro",
            freqContAlunoProf: "Média",
            // desistencia
            flagDesistencia: false,
            nNotasAbaixoMedia: 3,
            // reutilizaveis
            sentMsgs: "Neutro",
            nAcessos: 9,
            frequenciaLogin: "1,28",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 90,
        },
        {
            id: 4,
            nome: "Joaquina Paulina de Souza",
            email: "joaquina@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 2,
            nPostsForunsAv: 1,
            quizzesRealiz: "0%",
            tarefasEnv: "0%",
            tempoMedio: 5,
            // desempenho
            flagDesempenho: 2,
            mediaNotas: "4.5",
            compMedia: 65,
            ativAbaixoMedia: 8,
            // motivacao
            flagMotivacao: 2,
            partForunsNaoObrig: "20%",
            nVisuCompl: 10,
            nInter: 3,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 2,
            nMsgsAlunoProf: 0,
            nMsgsPriv: 0,
            partForunsDocente: "25%",
            sentMsgsPriv: "Negativo",
            freqContAlunoProf: "Baixa",
            // desistencia
            flagDesistencia: true,
            nNotasAbaixoMedia: 8,
            // reutilizaveis
            sentMsgs: "Negativo",
            nAcessos: 0,
            frequenciaLogin: "0",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 85,
        },
        {
            id: 5,
            nome: "Maria dos Cravos",
            email: "maria@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 1,
            nPostsForunsAv: 5,
            quizzesRealiz: "70%",
            tarefasEnv: "90%",
            tempoMedio: 70,
            // desempenho
            flagDesempenho: 1,
            mediaNotas: "3.8",
            compMedia: 55,
            ativAbaixoMedia: 6,
            // motivacao
            flagMotivacao: 1,
            partForunsNaoObrig: "15%",
            nVisuCompl: 8,
            nInter: 2,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 1,
            nMsgsAlunoProf: 1,
            nMsgsPriv: 0,
            partForunsDocente: "20%",
            sentMsgsPriv: "Negativo",
            freqContAlunoProf: "Baixa",
            // desistencia
            flagDesistencia: true,
            nNotasAbaixoMedia: 6,
            // reutilizaveis
            sentMsgs: "Negativo",
            nAcessos: 4,
            frequenciaLogin: "0,57",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 80,
        },
        {
            id: 6,
            nome: "Rita Lobaco",
            email: "rita@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 3,
            nPostsForunsAv: 6,
            quizzesRealiz: "70%",
            tarefasEnv: "75%",
            tempoMedio: 75,
            // desempenho
            flagDesempenho: 3,
            mediaNotas: "7.0",
            compMedia: 95,
            ativAbaixoMedia: 2,
            // motivacao
            flagMotivacao: 3,
            partForunsNaoObrig: "65%",
            nVisuCompl: 30,
            nInter: 18,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 3,
            nMsgsAlunoProf: 3,
            nMsgsPriv: 1,
            partForunsDocente: "80%",
            sentMsgsPriv: "Neutro",
            freqContAlunoProf: "Média",
            // desistencia
            flagDesistencia: false,
            nNotasAbaixoMedia: 2,
            // reutilizaveis
            sentMsgs: "Neutro",
            nAcessos: 6,
            frequenciaLogin: "0,86",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 75,
        },
        {
            id: 7,
            nome: "Luiz Pereira",
            email: "luiz@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 4,
            nPostsForunsAv: 0,
            quizzesRealiz: "20%",
            tarefasEnv: "0%",
            tempoMedio: 30,
            // desempenho
            flagDesempenho: 2,
            mediaNotas: "5.2",
            compMedia: 75,
            ativAbaixoMedia: 5,
            // motivacao
            flagMotivacao: 2,
            partForunsNaoObrig: "30%",
            nVisuCompl: 15,
            nInter: 5,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 2,
            nMsgsAlunoProf: 1,
            nMsgsPriv: 0,
            partForunsDocente: "40%",
            sentMsgsPriv: "Negativo",
            freqContAlunoProf: "Baixa",
            // desistencia
            flagDesistencia: true,
            nNotasAbaixoMedia: 5,
            // reutilizaveis
            sentMsgs: "Negativo",
            nAcessos: 1,
            frequenciaLogin: "0,14",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 70,
        },
        {
            id: 8,
            nome: "Maria dos Cravos",
            email: "maria@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 1,
            nPostsForunsAv: 5,
            quizzesRealiz: "70%",
            tarefasEnv: "90%",
            tempoMedio: 70,
            // desempenho
            flagDesempenho: 1,
            mediaNotas: "3.8",
            compMedia: 55,
            ativAbaixoMedia: 6,
            // motivacao
            flagMotivacao: 1,
            partForunsNaoObrig: "15%",
            nVisuCompl: 8,
            nInter: 2,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 1,
            nMsgsAlunoProf: 1,
            nMsgsPriv: 0,
            partForunsDocente: "20%",
            sentMsgsPriv: "Negativo",
            freqContAlunoProf: "Baixa",
            // desistencia
            flagDesistencia: true,
            nNotasAbaixoMedia: 6,
            // reutilizaveis
            sentMsgs: "Negativo",
            nAcessos: 4,
            frequenciaLogin: "0,57",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 65,
        },
        {
            id: 9,
            nome: "Rita Lobaco",
            email: "rita@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 3,
            nPostsForunsAv: 6,
            quizzesRealiz: "70%",
            tarefasEnv: "75%",
            tempoMedio: 75,
            // desempenho
            flagDesempenho: 3,
            mediaNotas: "7.0",
            compMedia: 95,
            ativAbaixoMedia: 2,
            // motivacao
            flagMotivacao: 3,
            partForunsNaoObrig: "65%",
            nVisuCompl: 30,
            nInter: 18,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 3,
            nMsgsAlunoProf: 3,
            nMsgsPriv: 1,
            partForunsDocente: "80%",
            sentMsgsPriv: "Neutro",
            freqContAlunoProf: "Média",
            // desistencia
            flagDesistencia: false,
            nNotasAbaixoMedia: 2,
            // reutilizaveis
            sentMsgs: "Neutro",
            nAcessos: 6,
            frequenciaLogin: "0,86",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 60,
        },
        {
            id: 10,
            nome: "Luiz Pereira",
            email: "luiz@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 4,
            nPostsForunsAv: 0,
            quizzesRealiz: "20%",
            tarefasEnv: "0%",
            tempoMedio: 30,
            // desempenho
            flagDesempenho: 2,
            mediaNotas: "5.2",
            compMedia: 75,
            ativAbaixoMedia: 5,
            // motivacao
            flagMotivacao: 2,
            partForunsNaoObrig: "30%",
            nVisuCompl: 15,
            nInter: 5,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 2,
            nMsgsAlunoProf: 1,
            nMsgsPriv: 0,
            partForunsDocente: "40%",
            sentMsgsPriv: "Negativo",
            freqContAlunoProf: "Baixa",
            // desistencia
            flagDesistencia: true,
            nNotasAbaixoMedia: 5,
            // reutilizaveis
            sentMsgs: "Negativo",
            nAcessos: 1,
            frequenciaLogin: "0,14",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 55,
        },
        {
            id: 11,
            nome: "Maria dos Cravos",
            email: "maria@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 1,
            nPostsForunsAv: 5,
            quizzesRealiz: "70%",
            tarefasEnv: "90%",
            tempoMedio: 70,
            // desempenho
            flagDesempenho: 1,
            mediaNotas: "3.8",
            compMedia: 55,
            ativAbaixoMedia: 6,
            // motivacao
            flagMotivacao: 1,
            partForunsNaoObrig: "15%",
            nVisuCompl: 8,
            nInter: 2,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 1,
            nMsgsAlunoProf: 1,
            nMsgsPriv: 0,
            partForunsDocente: "20%",
            sentMsgsPriv: "Negativo",
            freqContAlunoProf: "Baixa",
            // desistencia
            flagDesistencia: true,
            nNotasAbaixoMedia: 6,
            // reutilizaveis
            sentMsgs: "Negativo",
            nAcessos: 4,
            frequenciaLogin: "0,57",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
        },
        {
            id: 12,
            nome: "Rita Lobaco",
            email: "rita@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 3,
            nPostsForunsAv: 6,
            quizzesRealiz: "70%",
            tarefasEnv: "75%",
            tempoMedio: 75,
            // desempenho
            flagDesempenho: 3,
            mediaNotas: "7.0",
            compMedia: 95,
            ativAbaixoMedia: 2,
            // motivacao
            flagMotivacao: 3,
            partForunsNaoObrig: "65%",
            nVisuCompl: 30,
            nInter: 18,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 3,
            nMsgsAlunoProf: 3,
            nMsgsPriv: 1,
            partForunsDocente: "80%",
            sentMsgsPriv: "Neutro",
            freqContAlunoProf: "Média",
            // desistencia
            flagDesistencia: false,
            nNotasAbaixoMedia: 2,
            // reutilizaveis
            sentMsgs: "Neutro",
            nAcessos: 6,
            frequenciaLogin: "0,86",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 50,
        },
        {
            id: 13,
            nome: "Luiz Pereira",
            email: "luiz@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 4,
            nPostsForunsAv: 0,
            quizzesRealiz: "20%",
            tarefasEnv: "0%",
            tempoMedio: 30,
            // desempenho
            flagDesempenho: 2,
            mediaNotas: "5.2",
            compMedia: 75,
            ativAbaixoMedia: 5,
            // motivacao
            flagMotivacao: 2,
            partForunsNaoObrig: "30%",
            nVisuCompl: 15,
            nInter: 5,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 2,
            nMsgsAlunoProf: 1,
            nMsgsPriv: 0,
            partForunsDocente: "40%",
            sentMsgsPriv: "Negativo",
            freqContAlunoProf: "Baixa",
            // desistencia
            flagDesistencia: true,
            nNotasAbaixoMedia: 5,
            // reutilizaveis
            sentMsgs: "Negativo",
            nAcessos: 1,
            frequenciaLogin: "0,14",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 45,
        },
        {
            id: 14,
            nome: "Maria dos Cravos",
            email: "maria@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 1,
            nPostsForunsAv: 5,
            quizzesRealiz: "70%",
            tarefasEnv: "90%",
            tempoMedio: 70,
            // desempenho
            flagDesempenho: 1,
            mediaNotas: "3.8",
            compMedia: 55,
            ativAbaixoMedia: 6,
            // motivacao
            flagMotivacao: 1,
            partForunsNaoObrig: "15%",
            nVisuCompl: 8,
            nInter: 2,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 1,
            nMsgsAlunoProf: 1,
            nMsgsPriv: 0,
            partForunsDocente: "20%",
            sentMsgsPriv: "Negativo",
            freqContAlunoProf: "Baixa",
            // desistencia
            flagDesistencia: true,
            nNotasAbaixoMedia: 6,
            // reutilizaveis
            sentMsgs: "Negativo",
            nAcessos: 4,
            frequenciaLogin: "0,57",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 40,
        },
        {
            id: 15,
            nome: "Rita Lobaco",
            email: "rita@gmail.com",
            graduacao: "Engenharia Civil",
            cidade: "Montes Claros",
            polo: "Montes Claros",
            primeiroAcesso: "14/04/2018 ás 13:33",
            ultimoAcesso: "24/10/2023 às 12:52",
            // engajamento
            flagEngajamento: 3,
            nPostsForunsAv: 6,
            quizzesRealiz: "70%",
            tarefasEnv: "75%",
            tempoMedio: 75,
            // desempenho
            flagDesempenho: 3,
            mediaNotas: "7.0",
            compMedia: 95,
            ativAbaixoMedia: 2,
            // motivacao
            flagMotivacao: 3,
            partForunsNaoObrig: "65%",
            nVisuCompl: 30,
            nInter: 18,
            // profundidade cognitiva
            flagProfCog: 3,
            profCogForuns: 3,
            profCogQuizzes: 3,
            profCogTarefas: 3,
            // relacao aluno-professor
            flagRelAlunoProf: 3,
            nMsgsAlunoProf: 3,
            nMsgsPriv: 1,
            partForunsDocente: "80%",
            sentMsgsPriv: "Neutro",
            freqContAlunoProf: "Média",
            // desistencia
            flagDesistencia: false,
            nNotasAbaixoMedia: 2,
            // reutilizaveis
            sentMsgs: "Neutro",
            nAcessos: 6,
            frequenciaLogin: "0,86",
            detalhes: <FaPlus className='text-2xl text-gray-700' />,
            //temporarios
            value: 35
        },
    ];
}

export function getCursos() {
    return [
        {
            id: 222,
            shortname: 'MAT050',
            nome: 'Equações Diferenciais I',
            data: '2024.3',
            value: 95,
            // flags
            flagEngajamento: 4,
            flagMotivacao: 4,
            flagDesempenho: 4,
            flagRelAlunoProf: 4,
            flagProfCog: 3,
            flagDesistencia: false,
        },
        {
            id: 223,
            shortname: 'DCC263',
            nome: 'Teoria dos Compiladores',
            data: '2024.3',
            value: 90,
            // flags
            flagEngajamento: 3,
            flagMotivacao: 3,
            flagDesempenho: 3,
            flagRelAlunoProf: 3,
            flagProfCog: 3,
            flagDesistencia: false,
        },
        {
            id: 224,
            shortname: 'FIS003',
            nome: 'Física III',
            data: '2024.3',
            value: 85,
            // flags
            flagEngajamento: 2,
            flagMotivacao: 2,
            flagDesempenho: 2,
            flagRelAlunoProf: 2,
            flagProfCog: 3,
            flagDesistencia: false,
        },
        {
            id: 225,
            shortname: 'FIS001',
            nome: 'Física I',
            data: '2024.3',
            value: 80,
            // flags
            flagEngajamento: 1,
            flagMotivacao: 1,
            flagDesempenho: 1,
            flagRelAlunoProf: 1,
            flagProfCog: 3,
            flagDesistencia: false,
        },
    ];
}
